name: Test breadcrumb fix

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install
      - run: pnpm eslint
      - run: pnpm compile
      - run: pnpm compile-rtl
      - run: pnpm build-scss
